local InitFuncs = require "us4l.internals.MasterTable.InitFunctions"

local UCharInit = InitFuncs.UCharInit

UCharInit{ codepoint = 0x1F86F; name = "wideheadedsouthwestbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED SOUTH WEST BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F870; name = "wideheadedleftwardsmediumbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED LEFTWARDS MEDIUM BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F871; name = "wideheadedupwardsmediumbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED UPWARDS MEDIUM BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F872; name = "wideheadedrightwardsmediumbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED RIGHTWARDS MEDIUM BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F873; name = "wideheadeddownwardsmediumbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED DOWNWARDS MEDIUM BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F874; name = "wideheadednorthwestmediumbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED NORTH WEST MEDIUM BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F875; name = "wideheadednortheastmediumbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED NORTH EAST MEDIUM BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F876; name = "wideheadedsoutheastmediumbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED SOUTH EAST MEDIUM BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F877; name = "wideheadedsouthwestmediumbarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED SOUTH WEST MEDIUM BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F878; name = "wideheadedleftwardsheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED LEFTWARDS HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F879; name = "wideheadedupwardsheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED UPWARDS HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F87A; name = "wideheadedrightwardsheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED RIGHTWARDS HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F87B; name = "wideheadeddownwardsheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED DOWNWARDS HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F87C; name = "wideheadednorthwestheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED NORTH WEST HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F87D; name = "wideheadednortheastheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED NORTH EAST HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F87E; name = "wideheadedsoutheastheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED SOUTH EAST HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F87F; name = "wideheadedsouthwestheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED SOUTH WEST HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F880; name = "wideheadedleftwardsveryheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED LEFTWARDS VERY HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F881; name = "wideheadedupwardsveryheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED UPWARDS VERY HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F882; name = "wideheadedrightwardsveryheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED RIGHTWARDS VERY HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F883; name = "wideheadeddownwardsveryheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED DOWNWARDS VERY HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F884; name = "wideheadednorthwestveryheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED NORTH WEST VERY HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F885; name = "wideheadednortheastveryheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED NORTH EAST VERY HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F886; name = "wideheadedsoutheastveryheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED SOUTH EAST VERY HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F887; name = "wideheadedsouthwestveryheavybarbarrow"; numericcanonicalcombiningclass = 0; originalname = "WIDE-HEADED SOUTH WEST VERY HEAVY BARB ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F890; name = "leftwardstrianglearrowhead"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS TRIANGLE ARROWHEAD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F891; name = "upwardstrianglearrowhead"; numericcanonicalcombiningclass = 0; originalname = "UPWARDS TRIANGLE ARROWHEAD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F892; name = "rightwardstrianglearrowhead"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS TRIANGLE ARROWHEAD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F893; name = "downwardstrianglearrowhead"; numericcanonicalcombiningclass = 0; originalname = "DOWNWARDS TRIANGLE ARROWHEAD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F894; name = "leftwardswhitearrowwithintrianglearrowhead"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F895; name = "upwardswhitearrowwithintrianglearrowhead"; numericcanonicalcombiningclass = 0; originalname = "UPWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F896; name = "rightwardswhitearrowwithintrianglearrowhead"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F897; name = "downwardswhitearrowwithintrianglearrowhead"; numericcanonicalcombiningclass = 0; originalname = "DOWNWARDS WHITE ARROW WITHIN TRIANGLE ARROWHEAD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F898; name = "leftwardsarrowwithnotchedtail"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS ARROW WITH NOTCHED TAIL"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F899; name = "upwardsarrowwithnotchedtail"; numericcanonicalcombiningclass = 0; originalname = "UPWARDS ARROW WITH NOTCHED TAIL"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F89A; name = "rightwardsarrowwithnotchedtail"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS ARROW WITH NOTCHED TAIL"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F89B; name = "downwardsarrowwithnotchedtail"; numericcanonicalcombiningclass = 0; originalname = "DOWNWARDS ARROW WITH NOTCHED TAIL"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F89C; name = "heavyarrowshaftwidthone"; numericcanonicalcombiningclass = 0; originalname = "HEAVY ARROW SHAFT WIDTH ONE"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F89D; name = "heavyarrowshaftwidthtwothirds"; numericcanonicalcombiningclass = 0; originalname = "HEAVY ARROW SHAFT WIDTH TWO THIRDS"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F89E; name = "heavyarrowshaftwidthonehalf"; numericcanonicalcombiningclass = 0; originalname = "HEAVY ARROW SHAFT WIDTH ONE HALF"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F89F; name = "heavyarrowshaftwidthonethird"; numericcanonicalcombiningclass = 0; originalname = "HEAVY ARROW SHAFT WIDTH ONE THIRD"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A0; name = "leftwardsbottomshadedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS BOTTOM-SHADED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A1; name = "rightwardsbottomshadedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS BOTTOM SHADED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A2; name = "leftwardstopshadedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS TOP SHADED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A3; name = "rightwardstopshadedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS TOP SHADED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A4; name = "leftwardsleftshadedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS LEFT-SHADED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A5; name = "rightwardsrightshadedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS RIGHT-SHADED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A6; name = "leftwardsrightshadedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS RIGHT-SHADED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A7; name = "rightwardsleftshadedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS LEFT-SHADED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A8; name = "leftwardsbacktiltedshadowedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS BACK-TILTED SHADOWED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8A9; name = "rightwardsbacktiltedshadowedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS BACK-TILTED SHADOWED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8AA; name = "leftwardsfronttiltedshadowedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "LEFTWARDS FRONT-TILTED SHADOWED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8AB; name = "rightwardsfronttiltedshadowedwhitearrow"; numericcanonicalcombiningclass = 0; originalname = "RIGHTWARDS FRONT-TILTED SHADOWED WHITE ARROW"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8AC; name = "whitearrowshaftwidthone"; numericcanonicalcombiningclass = 0; originalname = "WHITE ARROW SHAFT WIDTH ONE"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
UCharInit{ codepoint = 0x1F8AD; name = "whitearrowshaftwidthtwothirds"; numericcanonicalcombiningclass = 0; originalname = "WHITE ARROW SHAFT WIDTH TWO THIRDS"; numericage = 7; generalcategory = [[othersymbol]]; graphemebase = true; age = [[v70]]; }
